/**
 * Database types - Auto-generated by Supabase CLI
 *
 * To generate these types, run:
 * npx supabase gen types typescript --project-id YOUR_PROJECT_ID > types/database.ts
 *
 * Or with local development:
 * npx supabase gen types typescript --local > types/database.ts
 */

// Placeholder types until Supabase tables are created and types are generated
// These will be replaced by auto-generated types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string | null;
          phone: string | null;
          first_name: string | null;
          last_name: string | null;
          department_id: string | null;
          position: string | null;
          preferred_language_id: string | null;
          onboarding_completed: boolean;
          onboarding_purpose: "SEARCH" | "REGISTER" | "BOTH" | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email?: string | null;
          phone?: string | null;
          first_name?: string | null;
          last_name?: string | null;
          department_id?: string | null;
          position?: string | null;
          preferred_language_id?: string | null;
          onboarding_completed?: boolean;
          onboarding_purpose?: "SEARCH" | "REGISTER" | "BOTH" | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string | null;
          phone?: string | null;
          first_name?: string | null;
          last_name?: string | null;
          department_id?: string | null;
          position?: string | null;
          preferred_language_id?: string | null;
          onboarding_completed?: boolean;
          onboarding_purpose?: "SEARCH" | "REGISTER" | "BOTH" | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      companies: {
        Row: {
          id: string;
          name: string;
          sector_id: string;
          country: string;
          address: string | null;
          rcs: string | null;
          primary_phone: string | null;
          primary_email: string | null;
          linkedin_url: string | null;
          latitude: number | null;
          longitude: number | null;
          is_premium: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          sector_id: string;
          country: string;
          address?: string | null;
          rcs?: string | null;
          primary_phone?: string | null;
          primary_email?: string | null;
          linkedin_url?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          is_premium?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          sector_id?: string;
          country?: string;
          address?: string | null;
          rcs?: string | null;
          primary_phone?: string | null;
          primary_email?: string | null;
          linkedin_url?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          is_premium?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_companies: {
        Row: {
          id: string;
          user_id: string;
          company_id: string;
          role: "admin" | "profile_manager" | "payment_manager" | "user";
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          company_id: string;
          role?: "admin" | "profile_manager" | "payment_manager" | "user";
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          company_id?: string;
          role?: "admin" | "profile_manager" | "payment_manager" | "user";
          created_at?: string;
        };
      };
      departments: {
        Row: {
          id: string;
          name_key: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name_key: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          name_key?: string;
          created_at?: string;
        };
      };
      sectors: {
        Row: {
          id: string;
          name_key: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name_key: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          name_key?: string;
          created_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      onboarding_purpose: "SEARCH" | "REGISTER" | "BOTH";
      company_role: "admin" | "profile_manager" | "payment_manager" | "user";
    };
  };
}

// Convenience types
export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];
export type InsertTables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];
export type UpdateTables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];
export type Enums<T extends keyof Database["public"]["Enums"]> =
  Database["public"]["Enums"][T];

// Table row types
export type DbUser = Tables<"users">;
export type DbCompany = Tables<"companies">;
export type DbUserCompany = Tables<"user_companies">;
export type DbDepartment = Tables<"departments">;
export type DbSector = Tables<"sectors">;

// Aliases for backwards compatibility and cleaner imports
export type User = DbUser;
export type Company = DbCompany;
export type UserCompany = DbUserCompany;

// Insert types
export type UserInsert = InsertTables<"users">;
export type CompanyInsert = InsertTables<"companies">;
export type UserCompanyInsert = InsertTables<"user_companies">;

// Update types
export type UserUpdate = UpdateTables<"users">;
export type CompanyUpdate = UpdateTables<"companies">;
